name: bank_flutter
description: Um aplicativo de banco digital desenvolvido com Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  intl: ^0.19.0
  fl_chart: ^0.66.2
  share_plus: ^7.2.2
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  permission_handler: ^11.2.1
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Montserrat-Light.ttf
  #         weight: 300